"""
Mark main_effect fields as unverified for non-Core paper JSONs.

Context (Issue M3 from Stage 0 Audit):
  Core 57 papers have author-verified main_effect values extracted from
  the original papers. Expansion 80 + Extended 125 = 205 papers had
  main_effect generated by GPT-4o from only title+abstract — those
  specific numeric values (e.g., "β = -0.23") are NOT in the paper,
  they are plausibility guesses.

This script adds two fields to each non-Core paper's ground_truth:
  - main_effect_verified:  false
  - main_effect_source:    "gpt4o_inferred_from_metadata"

Core papers (1-57) are left unchanged: their main_effect is author-verified.

Usage:
    python3 scripts/mark_unverified_main_effects.py
    python3 scripts/mark_unverified_main_effects.py --dry-run
"""

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
PAPERS_DIR = PROJECT_ROOT / "experiments/exp_a/papers"

CORE_MAX_ID = 57   # papers 1..57 are Core tier (author-verified)

NOW = datetime.now(timezone.utc).isoformat()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    paper_files = sorted(PAPERS_DIR.glob("paper_*.json"),
                         key=lambda p: int(p.stem.split("_")[1]))

    n_core = 0
    n_marked = 0
    n_skipped = 0  # already marked / no main_effect
    n_error = 0

    for pf in paper_files:
        try:
            d = json.load(open(pf))
            pid = d["paper_id"]
            num = int(pid.split("_")[1])
        except Exception as e:
            n_error += 1
            continue

        if num <= CORE_MAX_ID:
            n_core += 1
            continue  # Core tier: leave main_effect unchanged

        gt = d.setdefault("ground_truth", {})
        if "main_effect" not in gt:
            n_skipped += 1
            continue

        if gt.get("main_effect_verified") is False:
            n_skipped += 1  # already marked
            continue

        # Mark as unverified
        gt["main_effect_verified"] = False
        gt["main_effect_source"] = "gpt4o_inferred_from_metadata"
        gt["main_effect_note"] = (
            "This value was generated by GPT-4o from the paper's title + "
            "abstract, NOT extracted from the paper's tables. It serves as "
            "a directional plausibility indicator only; the specific number "
            "should not be compared to LLM outputs. Pillar A / L2b+ analysis "
            "uses only synthetic Exp B data and is unaffected by this field."
        )

        # Audit trail
        d.setdefault("_fix_notes", []).append({
            "fix_id": "issue_M3_mark_unverified_main_effect",
            "applied_at": NOW,
            "tier": "Extended" if num > 137 else "Expansion",
        })

        if not args.dry_run:
            with open(pf, "w") as f:
                json.dump(d, f, indent=2, ensure_ascii=False)
        n_marked += 1

    print(f"{'[DRY RUN]' if args.dry_run else '[APPLIED]'}")
    print(f"  Core tier (1..{CORE_MAX_ID}, left unchanged): {n_core}")
    print(f"  Marked as unverified (Expansion + Extended): {n_marked}")
    print(f"  Skipped (no main_effect / already marked):   {n_skipped}")
    print(f"  Errors:                                     {n_error}")


if __name__ == "__main__":
    main()
