"""
Step B — Check fidelity of GPT-4o's institutional_context (and RQ/DD)
against the REAL published abstract (from Step A).

Uses Claude Opus 4.7 as an independent judge. For each paper:
  • Input:  real_abstract (from OpenAlex) + institutional_context (paper JSON)
  • Output: {"fidelity": "faithful" | "partial" | "diverges",
             "key_discrepancies": [...],
             "confidence": "high" | "medium" | "low"}

Inputs:
  audit/real_abstracts.json            (Step A output)
  experiments/exp_a/papers/paper_XX.json

Outputs:
  audit/abstract_fidelity.json         (per-paper judgement)
  audit/abstract_fidelity_summary.md   (human-readable summary + histogram)

This diagnostic decides whether we need to regenerate RQ/DD/IC:
  - > 90% faithful  →  disclose in limitations, no action
  - 70-90% faithful →  regenerate divergent ones only
  - < 70% faithful  →  full regenerate + re-run experiments
"""

import argparse
import json
import os
import time
from pathlib import Path
from collections import Counter, defaultdict

from dotenv import load_dotenv
load_dotenv()

ROOT         = Path(__file__).parent.parent.parent
REAL_ABS     = ROOT / "audit/real_abstracts.json"
PAPERS_DIR   = ROOT / "experiments/exp_a/papers"
OUT_JSON     = ROOT / "audit/abstract_fidelity.json"
OUT_MD       = ROOT / "audit/abstract_fidelity_summary.md"

MODEL = "claude-opus-4-7"

SYSTEM = """You are an expert empirical-finance economist evaluating
whether a benchmark dataset's paper description faithfully represents
the actual published abstract of a paper.

Given:
  A. The REAL published abstract (from OpenAlex)
  B. A benchmark "institutional_context" (generated by GPT-4o from
     paper metadata during benchmark construction)

Judge whether (B) is a faithful characterization of (A):

  "faithful" — (B) accurately represents the paper's setting, method
               (without naming it), and main finding; a reader of (B)
               would recognize (A).

  "partial"  — (B) captures the general topic but is missing key
               elements (wrong setting, incomplete data description,
               or subtle inaccuracies) that might mislead a downstream
               LLM trying to infer the method.

  "diverges" — (B) materially differs from (A): wrong subject matter,
               wrong institutional setup, fabricated details not in
               the abstract, or misses the paper's actual point.

Return ONLY a JSON object:
{
  "fidelity":        "faithful" | "partial" | "diverges",
  "key_discrepancies": ["<one-line discrepancy>", ...]   // empty if faithful
  "confidence":      "high" | "medium" | "low"
}

Be strict. If institutional_context appears to be reasonable but you
can't verify alignment from the real abstract, mark "partial" with
low confidence rather than guessing "faithful"."""


USER_TEMPLATE = """Paper title (both refer to the same paper):
{title}

================================================================
A. REAL abstract (from OpenAlex — this is the published ground truth):
{real_abstract}

================================================================
B. institutional_context (from benchmark — generated by GPT-4o):
{institutional_context}

================================================================
Evaluate fidelity per the schema."""


def find_paper_file(pid: str) -> Path | None:
    hits = list(PAPERS_DIR.glob(f"{pid}_*.json")) + list(PAPERS_DIR.glob(f"{pid}.json"))
    return hits[0] if hits else None


def call_opus(real_abs: str, institutional: str, title: str) -> dict:
    import anthropic
    client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
    user = USER_TEMPLATE.format(
        title=title[:200],
        real_abstract=real_abs[:2500],
        institutional_context=institutional[:2500],
    )
    r = client.messages.create(
        model=MODEL,
        max_tokens=600,
        system=SYSTEM,
        messages=[{"role": "user", "content": user}],
    )
    raw = r.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```", 2)[1]
        if raw.startswith("json"): raw = raw[4:]
        raw = raw.strip("` \n")
    return json.loads(raw)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=None,
                    help="only judge the first N papers (for testing)")
    ap.add_argument("--resume", action="store_true", default=True)
    args = ap.parse_args()

    # Load Step A output
    if not REAL_ABS.exists():
        print(f"ERROR: {REAL_ABS} not found. Run pull_real_abstracts.py first.")
        return
    real_abstracts = {r["paper_id"]: r for r in json.loads(REAL_ABS.read_text())}
    print(f"Loaded {len(real_abstracts)} real abstracts")

    # Load existing cache
    cache = {}
    if OUT_JSON.exists() and args.resume:
        cache = {r["paper_id"]: r for r in json.loads(OUT_JSON.read_text())}
        print(f"  resuming; {len(cache)} already judged")

    papers = sorted(real_abstracts.keys(), key=lambda p: int(p.split("_")[1]))
    if args.limit: papers = papers[:args.limit]
    print(f"Judging {len(papers)} papers with {MODEL}...")

    results = []
    for i, pid in enumerate(papers, 1):
        if pid in cache and "fidelity" in cache[pid]:
            results.append(cache[pid])
            continue

        abs_row = real_abstracts[pid]
        real_abs = abs_row.get("real_abstract")
        if not real_abs:
            row = {"paper_id": pid, "fidelity": "no_real_abstract",
                   "error": abs_row.get("error", "unknown")}
            results.append(row); cache[pid] = row
            continue

        pf = find_paper_file(pid)
        if not pf:
            row = {"paper_id": pid, "fidelity": "error",
                   "error": "paper JSON not found"}
            results.append(row); cache[pid] = row
            continue

        paper = json.loads(pf.read_text())
        institutional = paper.get("institutional_context", "")
        title = paper.get("title", "")

        try:
            verdict = call_opus(real_abs, institutional, title)
            row = {
                "paper_id":          pid,
                "title":             title[:100],
                "fidelity":          verdict.get("fidelity"),
                "key_discrepancies": verdict.get("key_discrepancies", []),
                "confidence":        verdict.get("confidence"),
            }
        except Exception as e:
            row = {"paper_id": pid, "fidelity": "error", "error": str(e)[:200]}

        results.append(row)
        cache[pid] = row

        mark = {"faithful": "✓", "partial": "~", "diverges": "✗"}.get(row["fidelity"], "?")
        print(f"  [{i}/{len(papers)}] {pid}: {mark} {row.get('fidelity', 'error')}")

        time.sleep(0.2)
        # incremental flush every 20
        if i % 20 == 0:
            OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
            OUT_JSON.write_text(json.dumps(list(cache.values()),
                                            indent=2, ensure_ascii=False))

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(list(cache.values()),
                                    indent=2, ensure_ascii=False))

    # Summary
    fidelity_counter = Counter(r.get("fidelity", "error") for r in results)
    total = len(results)
    judged = sum(v for k, v in fidelity_counter.items()
                  if k in ("faithful", "partial", "diverges"))

    md = [
        "# Abstract Fidelity Summary (Step B)",
        "",
        f"**Model judge**: {MODEL}",
        f"**Papers judged**: {judged} / {total}",
        "",
        "## Distribution",
        "",
        "| Verdict | Count | % of judged |",
        "|---|---:|---:|",
    ]
    for k in ("faithful", "partial", "diverges"):
        n = fidelity_counter.get(k, 0)
        pct = n / judged * 100 if judged else 0
        md.append(f"| {k} | {n} | {pct:.1f}% |")

    md += ["", "## Non-judged", "",
           "| Reason | Count |",
           "|---|---:|"]
    for k, n in fidelity_counter.items():
        if k not in ("faithful", "partial", "diverges"):
            md.append(f"| {k} | {n} |")

    faithful_rate = fidelity_counter.get("faithful", 0) / judged if judged else 0
    md += [
        "",
        "## Decision guide",
        "",
        f"- Faithful rate: **{faithful_rate*100:.1f}%**",
        f"- {'✅ ≥ 90%: disclose in limitations, no action needed' if faithful_rate >= 0.9 else ''}",
        f"- {'🟡 70-90%: regenerate divergent ones only (see diverges list)' if 0.7 <= faithful_rate < 0.9 else ''}",
        f"- {'🔴 < 70%: full regeneration + re-run experiments recommended' if faithful_rate < 0.7 else ''}",
        "",
        "## Sample discrepancies (top 10)",
        "",
    ]
    bad = [r for r in results if r.get("fidelity") in ("partial", "diverges")]
    for r in bad[:10]:
        md.append(f"- **{r['paper_id']}** ({r['fidelity']}): "
                  + ("; ".join(r.get("key_discrepancies", [])) or "no details"))

    OUT_MD.write_text("\n".join(md) + "\n")
    print()
    print(f"Results: {OUT_JSON}")
    print(f"Summary: {OUT_MD}")
    print()
    print(f"Faithful rate: {faithful_rate*100:.1f}%")


if __name__ == "__main__":
    main()
